apiVersion: v1
kind: Service
metadata:
  name: book-info
spec:
  type: NodePort
  ports:
    - port: 8081
      nodePort: 30001
      targetPort: 8081
  selector:
    app: book-info
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: book-info
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-info
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: book-info
    spec:
      containers:
        - image: rezacomplete/book-info
          name: book-info
          ports:
            - containerPort: 8081
