apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  type: NodePort
  ports:
    - port: 8083
      nodePort: 30003
      targetPort: 8083
  selector:
    app: book-catalog
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
        - image: rezacomplete/book-catalog
          name: book-catalog
          ports:
            - containerPort: 8083

