apiVersion: v1
kind: Service
metadata:
  name: book-rating
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30002
  selector:
    app: book-rating
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: book-rating
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-rating
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: book-rating
    spec:
      containers:
        - image: rezacomplete/book-rating
          name: book-rating
          ports:
            - containerPort: 8082
