version: "3.5"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bookstore
    networks:
      - book-net
  book-info:
    build: ../BookInfo
    ports:
      - target: 8081
        published: 8081
    networks:
      - book-net
    depends_on:
      - db
  book-rating:
    build: ../BookRating
    container_name: book-rating
    ports:
      - target: 8082
        published: 8082
    networks:
      - book-net
  book-catalog:
    build: .
    container_name: book-catalog
    ports:
      - target: 8083
        published: 8083
    networks:
      - book-net
    depends_on:
      - book-info
      - book-rating


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - book-net

networks:
  book-net:
